### ISSUE TITLE
Add read_raw_xdf

### ISSUE THREAD

**Issue by MaxMascini** [mne-tools/mne-python#12985]
### Describe the new feature or enhancement

Port the xdf module (mnelab.io.xdf) from mnelab to mne-python. Currently, mnelab causes some dependency issues with numpy so we've had to copy and import the module separately. 
The mnelab module already has an integrated mne class and read_raw_xdf:
Resolving streams, converting to mne RawArray, resampling streams, and functionality of converting an automatically-detected marker stream to raw annotations, among others.

### Describe your proposed implementation

After basic testing on my end, the entire module appears already completely compatible with mne-python. Just integrating it into mne-python base package would be useful, and *hopefully* very easy.

### Describe possible alternatives

Create a new module that handles converting xdf to mne Raw array. Resolve streams, resample data, and functionality of converting a marker stream to raw annotations would be incredibly useful (and are already implement in mnelab's xdf module)

### Additional context

I would love to help, but I would not consider myself a weathered python developer. If someone can point me in the right direction with testing and where to plop the module, I would be than happy to make a pull request :)

**Comment by MaxMascini** [comment]
I noticed that there is an open pull request from 2022 #10420 - What was/is the status on this?

**Comment by mscheltienne** [comment]
That might also be useful for `mne-lsl` at some point.

**Comment by MaxMascini** [comment]
Pinging @cbrnr - Do you know what happened to the old PR to implement this?

**Comment by cbrnr** [comment]
Hi @MaxMascini! We never really decided what to do with it, and whether or not it is suitable for integration into MNE-Python.

Currently, there is a bug with our resampling implementation (https://github.com/cbrnr/mnelab/issues/385), which produces incorrect timings if the recording has gaps (this is hopefully a rare situation, but of course it can happen). So until this is fixed, it cannot be moved to MNE-Python.

May I ask what the dependency issues of MNELAB with NumPy are?

Incidentally, I've recently considered moving the XDF reader out of MNELAB into a lightweight package. This would make it easier for users to access the reader without the PySide6 dependencies. Migrating it to MNE-Python might be premature since various things (including the interface) might still be changing, and MNE-Python puts a strong emphasis on stability and backward compatibility, which I cannot (and don't want to) commit to yet.

**Comment by MaxMascini** [comment]
Thanks for getting back to me @cbrnr! I think it's an excellent middle-ground to move the XDF utilities to a lightweight module for now.

Regarding the dependency issues we've encountered, we believe that the dependency issues are related to numba/numpy (which may just be a conda/mamba dependency solver issue).

**When creating an environment from scratch**
with `mamba install python==3.12.7 mne mne-bids mnelab jupyterlab`

We get this when trying to import read_raw_xdf:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 17
     15 from mne_bids.stats import count_events
     16 from pyxdf import resolve_streams
---> 17 from mnelab.io.xdf import read_raw_xdf
     18 from xml.etree.ElementTree import ParseError

File c:\ProgramData\miniforge3\envs\mnelab-test\Lib\site-packages\mnelab\__init__.py:14
     11 from PySide6.QtGui import QIcon
     12 from PySide6.QtWidgets import QApplication
---> 14 from mnelab.mainwindow import MainWindow
     15 from mnelab.model import Model
     17 __version__ = "0.9.2"

File c:\ProgramData\miniforge3\envs\mnelab-test\Lib\site-packages\mnelab\mainwindow.py:33
     30 from pyxdf import resolve_streams
     32 from mnelab.dialogs import *  # noqa: F403
---> 33 from mnelab.io import writers
     34 from mnelab.io.mat import parse_mat
     35 from mnelab.io.npy import parse_npy

File c:\ProgramData\miniforge3\envs\mnelab-test\Lib\site-packages\mnelab\io\__init__.py:6
      1 # © MNELAB developers
      2 #
      3 # License: BSD (3-clause)
      5 from mnelab.io.readers import read_raw
----> 6 from mnelab.io.writers import write_raw, writers

File c:\ProgramData\miniforge3\envs\mnelab-test\Lib\site-packages\mnelab\io\writers.py:9
      7 import mne
      8 import numpy as np
----> 9 from numpy.rec import fromarrays
     10 from scipy.io import savemat
     13 def write_fif(fname, raw):

ModuleNotFoundError: No module named 'numpy.rec'
```


**When trying to create an environment with numpy>=2.1, we get this environment solving error and tree:**

```
LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides vc 9.* needed by numba-0.46.0-py27h0e003f4_1

Could not solve for environment specs
The following packages are incompatible
├─ mne >=1.8.0  is installable with the potential options
│  ├─ mne 1.8.0 would require
│  │  └─ numba with the potential options
│  │     ├─ numba 0.46.0 would require
│  │     │  └─ vc 9.* , which does not exist (perhaps a missing channel);
│  │     ├─ numba [0.46.0|0.47.0|0.48.0|0.50.1] would require
│  │     │  └─ numpy >=1.14.6,<1.21.0a0  with the potential options
│  │     │     ├─ numpy [1.14.6|1.15.4|1.16.2|1.16.3|1.16.5] would require
│  │     │     │  └─ vc 9.* , which does not exist (perhaps a missing channel);
│  │     │     ├─ numpy [1.14.6|1.15.0|1.15.1|1.15.2] would require
│  │     │     │  └─ openblas >=0.2.20,<0.2.21.0a0 , which requires
│  │     │     │     └─ vc 14 , which does not exist (perhaps a missing channel);
│  │     │     ├─ numpy [1.14.6|1.15.2|...|1.16.4], which can be installed;
│  │     │     ├─ numpy 1.16.4 would require
│  │     │     │  └─ python >=2.7,<2.8.0a0  but there are no viable options
│  │     │     │     ├─ python [2.7.12|2.7.13|2.7.14|2.7.15] would require
│  │     │     │     │  └─ vc 9.* , which does not exist (perhaps a missing channel);
│  │     │     │     └─ python 2.7.15 would require
│  │     │     │        └─ vc >=9,<10.0a0 , which does not exist (perhaps a missing channel);
│  │     │     ├─ numpy 1.16.5, which can be installed;
│  │     │     ├─ numpy [1.16.6|1.17.0|1.17.1|1.17.2|1.17.3], which can be installed;
│  │     │     ├─ numpy 1.17.5, which can be installed;
│  │     │     ├─ numpy [1.18.1|1.18.4|...|1.19.4], which can be installed;
│  │     │     └─ numpy [1.19.5|1.20.0|1.20.1|1.20.2|1.20.3], which can be installed;
│  │     ├─ numba [0.49.0|0.49.1] would require
│  │     │  └─ numpy >=1.14.6,<1.18.0  with the potential options
│  │     │     ├─ numpy [1.14.6|1.15.4|1.16.2|1.16.3|1.16.5], which cannot be installed (as previously explained);
│  │     │     ├─ numpy [1.14.6|1.15.0|1.15.1|1.15.2], which cannot be installed (as previously explained);
│  │     │     ├─ numpy [1.14.6|1.15.2|...|1.16.4], which can be installed;
│  │     │     ├─ numpy 1.16.4, which cannot be installed (as previously explained);
│  │     │     ├─ numpy 1.16.5, which can be installed;
│  │     │     ├─ numpy [1.16.6|1.17.0|1.17.1|1.17.2|1.17.3], which can be installed;
│  │     │     └─ numpy 1.17.5, which can be installed;
│  │     ├─ numba [0.51.0|0.51.1|0.51.2|0.52.0] would require
│  │     │  └─ numpy >=1.16.5,<1.21.0a0  with the potential options
│  │     │     ├─ numpy [1.14.6|1.15.4|1.16.2|1.16.3|1.16.5], which cannot be installed (as previously explained);
│  │     │     ├─ numpy 1.16.5, which can be installed;
│  │     │     ├─ numpy [1.16.6|1.17.0|1.17.1|1.17.2|1.17.3], which can be installed;
│  │     │     ├─ numpy 1.17.5, which can be installed;
│  │     │     ├─ numpy [1.18.1|1.18.4|...|1.19.4], which can be installed;
│  │     │     └─ numpy [1.19.5|1.20.0|1.20.1|1.20.2|1.20.3], which can be installed;
│  │     ├─ numba 0.53.0 would require
│  │     │  └─ numpy >=1.16.6,<1.21.0a0 , which can be installed;
│  │     ├─ numba [0.53.0|0.53.1] would require
│  │     │  └─ numpy >=1.19.5,<1.21.0a0 , which can be installed;
│  │     ├─ numba 0.53.1 would require
│  │     │  └─ numpy >=1.17.5,<1.21.0a0 , which can be installed;
│  │     ├─ numba [0.54.0|0.54.1] would require
│  │     │  └─ numpy >=1.17,<1.21 , which can be installed;
│  │     ├─ numba [0.55.0|0.55.1] would require
│  │     │  └─ numpy >=1.18,<1.22 , which can be installed;
│  │     ├─ numba 0.55.2 would require
│  │     │  └─ numpy >=1.18,<1.23 , which can be installed;
│  │     ├─ numba [0.56.2|0.56.3|0.56.4] would require
│  │     │  └─ numpy >=1.18,!=1.22.0,!=1.22.1,!=1.22.2,<1.24 , which can be installed;
│  │     ├─ numba [0.57.0|0.57.1] would require
│  │     │  └─ numpy >=1.21,!=1.22.0,!=1.22.1,!=1.22.2,<1.25 , which can be installed;
│  │     ├─ numba [0.58.1|0.59.0|0.59.1] would require
│  │     │  └─ numpy >=1.22.3,<1.27 , which can be installed;
│  │     └─ numba 0.60.0 would require
│  │        └─ numpy >=1.22.3,<2.1  with the potential options
│  │           ├─ numpy [1.22.3|1.22.4|...|2.0.2], which can be installed;
│  │           └─ numpy [2.0.0rc1|2.0.0rc2|2.1.0rc1|2.2.0rc1] would require
│  │              └─ _numpy_rc, which does not exist (perhaps a missing channel);
│  └─ mne 1.8.0 would require
│     └─ __osx, which is missing on the system;
└─ numpy >=2.1.*  is not installable because there are no viable options
   ├─ numpy [2.0.0rc1|2.0.0rc2|2.1.0rc1|2.2.0rc1], which cannot be installed (as previously explained);
   └─ numpy [2.1.0|2.1.1|2.1.2|2.1.3] conflicts with any installable versions previously reported.
```

Let me know if you have any ideas - or if you see something we've missed!

**Comment by cbrnr** [comment]
Hmmm, I don't use conda/mamba, but MNELAB only requires `numpy >= 2.0.0`, which should be installable according to the output. Did you specifically request `numpy >= 2.1.0`?

**Comment by cbrnr** [comment]
Also, maybe `np.rec.fromarrays` is not even necessary here. I think this is the only place where NumPy >= 2 is required (the import for versions < 2 would be `from numpy.core.records import fromarrays`). So it could be either a simple `try`/`except`, or even better, maybe record arrays are not even needed here. Would you have time to investigate and if you find a solution make a PR?

**Comment by aman-coder03** [comment]
following up from #13727 which was closed and pointed here...after reading through this thread... it looks like there are two concrete blockers, heterogeneous `sfreq` problem across streams, and resampling bug with gapped recordings

for `sfreq` problem, one practical approach would be to require the user to specify a `stream_id` upfront, which selects a single LSL stream and avoids multi sfreq issue entirely for the common case. Users who need multiple streams could be directed to `pyxdf` directly. This would cover probably 90% of real world use cases where someone just wants their EEG stream loaded

for resampling bug, that seems like something that needs to be fixed in the underlying implementation before anything gets merged regardless. I have already looked at the existing example at `examples/io/read_xdf.py` and the `misc` dataset test file, so I have a reasonable sense of where the implementation would live

is there a minimal version of `read_raw_xdf` with `stream_id` required that maintainers would consider merging, even if it does not handle every edge case yet?

**Comment by cbrnr** [comment]
I already fixed these problems, so you can just use `read_raw_xdf` from `mnelab` (https://github.com/cbrnr/mnelab).

**Comment by drammock** [comment]
I feel like [this comment](https://github.com/mne-tools/mne-python/pull/10420#issuecomment-1062205641) captures something important that isn't fixed by using MNELAB's reader:

>  from mnelab.io.xdf import read_raw_xdf required me to provide a streamid, meaning that I had to read the xdf files by hand using pyxdf and look at what every stream corresponds to before using the function. This is not a user friendly solution

The [parameter description for `stream_ids`](https://github.com/cbrnr/mnelab/blob/99a7483d6a26a1076799414ef60a2826ce3ce469/src/mnelab/io/xdf.py#L38-L40) says:

> A list of available streams can be obtained with `pyxdf.resolve_streams(fname)`.

... which is great, but at that point the user already needs to have imported pyxdf, and done some poking around to figure out which stream(s) are the right ones.

In light of all that, it seems like one or both of the following might be optimal:

1. a helper function to read and display relevant info from the XDF file (stream IDs, sfreqs, and modalities seems like the minimum necessary)
2. if the user tries to read a file and either (a) forgets to specify the stream IDs, or (2) requests streams with incompatible sfreqs, the error handling should call the helper function and print out its results so that the user can immediately correct their requested stream IDs without having to manually call the helper function .

As a side note, IIUC MNELAB requires specifying `fs_new` when reading multiple streams... having almost no experience with MNELAB and XDF files, I naively assumed `fs_new` would only be required if the multiple requested streams actually had different sfreqs. If we're going to migrate the XDF reader code into MNE-Python, I'd like it to be possible to request multiple streams and also omit `fs_new` and still have things work, in the case where all requested streams have the same sfreq.

**Comment by aman-coder03** [comment]
thanks!! @drammock that is really helpful framing...and interesting to see that the `stream_id` usability concern goes all the way back to the original PR in 2022, so it is clearly a real friction point worth solving properly

so if I understand correctly, the ideal interface would be something like...
- `read_xdf_info(fname)` as a standalone helper that lists all streams with their IDs, `sfreqs`, and channel types
- `read_raw_xdf(fname, stream_ids=None)` where `stream_ids` defaults to `None`,loads all streams if `sfreqs` are compatible and if there is a conflict it calls `read_xdf_info` internally and raises an informative error showing the user exactly what streams are available
- `fs_new` only required when requested streams actually have different `sfreqs`, omitting it should just work when all streams share the same `sfreq`

does that match what you have in mind? happy to draft a PR along those lines

**Comment by drammock** [comment]
> does that match what you have in mind?

yep. There may be some bikeshedding of the function and parameter names, but that's the behavior I'm imagining. I think we should await approval from @cbrnr before you proceed though, since the plan involves adapting his code from MNELAB... the license is compatible, but maybe he'll prefer to retain/share credit for the commits, or coordinate this change with corresponding changes in MNELAB.

**Comment by cbrnr** [comment]
Actually, resampling or interpolating is required if you want to load more than one stream, even if they have the same (nominal) sampling frequency. These streams come from different devices, and each sample has its own timestamp, so you need to bring everything together on the same time basis. Therefore, I don't think that loading an XDF file without specifying the stream(s) makes sense. If you want to do that, you could load all streams by default, but this requires resampling if there is more than one.

The helper function that shows all streams already exists, but if you want to have it in the same namespace as `read_raw_xdf` I'm happy to create an alias.

I would like to keep the reader in MNELAB, or maybe outsource it in a separate lightweight package as I've mentioned previously. If you want to take the code, the license is compatible, so feel free, but I will be maintaining the MNELAB functions and pyxdf and not a third implementation in MNE.

**Comment by cbrnr** [comment]
PS: I guess loading everything if there is only one stream (plus any marker streams) by default without specifying a stream ID might be OK, and printing/returning the list of streams otherwise would also work.

**Comment by aman-coder03** [comment]
thanks!! @cbrnr that is really helpful clarification on the resampling point...PS makes a lot of sense as a starting point. So the behavior would be
- one stream detected: load it automatically, no `stream_id` needed
- multiple streams detected: print available streams with their IDs, `sfreqs` and types, then ask the user to specify `stream_ids` explicitly
- marker streams always converted to annotations automatically

would you be comfortable with us reusing the MNELAB code under its existing license, with proper attribution in the file header? and if the helper function already exists in MNELAB, pointing to it directly in the error message might be cleaner than reimplementing it

**Comment by cbrnr** [comment]
Another option could be to add the MNE-related functionality directly to `pyxdf` as an extra (e.g., `pyxdf[mne]`), but I'm not sure if the `pyxdf` devs (which includes me) would want that.

**Comment by aman-coder03** [comment]
that is an interesting idea, though it would add complexity on the maintenance side. From a user perspective the simplest experience 
would still be `mne.io.read_raw_xdf()` sitting alongside all other readers, since that is where people would naturally look for it
happy to wait if you and the `pyxdf` devs want to discuss that direction first, but if the consensus is to go ahead with a direct mne implementation using the MNELAB code as a base, I am ready to start whenever you give the go ahead...

**Comment by cbrnr** [comment]
I have moved the XDF reader from MNELAB into a lightweight package called [MNExtend](https://github.com/cbrnr/mnextend/tree/main) (it doesn't depend on PySide6). Trying to load an XDF file without specifying the stream ID(s) also yields an informative error message:

```python
import mnextend
raw = mnextend.read_raw("~/Data/Biosignal Test Data/XDF/xdf_sample.xdf")
```

```
ValueError: Argument `stream_ids` is required (available regular stream IDs: 3, 2).
```

The package contains several additional things moved from MNELAB, e.g., ICLabel and support for MAT/NPY import.

**Comment by larsoner** [comment]
Closing as out of scope (use `mnextend`)!
