### ISSUE TITLE
Issues with CSP example

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-python#4407]
I noticed a number of issues here with the [CSP example](https://martinos.org/mne/stable/auto_examples/decoding/plot_decoding_csp_eeg.html#sphx-glr-auto-examples-decoding-plot-decoding-csp-eeg-py)

* It's using deprecated parameters: 'firwin2' and 'norm_trace=True'. In fact, the warning for the 'norm_trace' left me confused for 5 minutes because it was talking about a parameter that didn't actually exist. Finally, I figured it must be the one which is boolean.

* If I use the recommended parameters, the patterns now look quite different. 

![pattern_new](https://user-images.githubusercontent.com/15852194/28394468-80eb04ce-6ced-11e7-9edd-e24d6763c63b.png)

as opposed to

![pattern_old](https://martinos.org/mne/stable/_images/sphx_glr_plot_decoding_csp_eeg_001.png) on the website

Note the scale and see the last pattern.

* Finally, I was a bit mystified that 5 patterns were being plotted even though 4 components were estimated. The documentation tells me that the shape of patterns_ should be n_components x n_channels but I see that the shape is n_channels x n_channels

Sorry I don't have time to look into more detail at the moment but hopefully someone can take over

**Comment by jasmainak** [comment]
Also, I suspect the TimeDecoding class could be used to simplify the example quite a bit

**Comment by jaeilepp** [comment]
Most of the issues are already fixed in [dev](http://martinos.org/mne/dev/auto_examples/decoding/plot_decoding_csp_space.html?highlight=csp).
The number of components seems weird. Looks like only the number of filters is limited in the code. I suppose the ``patterns_`` should be as well.

**Comment by jasmainak** [comment]
See [here] (https://github.com/mne-tools/mne-python/blob/a2b75f7d06fd753b7732f71a1f92802abc28dd63/mne/decoding/csp.py#L131). The warning is also still broken and I see `norm_trace` is not set to True also in the dev version.
