### ISSUE TITLE
Error: mri_make_bem_surfaces has been removed from this version of freesurfer

### ISSUE THREAD

**Issue by RickLicona** [mne-tools/mne-python#8309]
Hi,

I was running the Python script "01-anatomy.py" of the GitHub project named mne-biomag-group-demo. However, the console throw the next message errors: 

![imagen](https://user-images.githubusercontent.com/22995049/94332557-e67a2600-ff9b-11ea-9438-0f22743c4214.png)
![imagen](https://user-images.githubusercontent.com/22995049/94335059-5c7f8c80-ff9e-11ea-8d0d-d91d06967616.png)

I have the MNE version 0.20.8 and 7.1.1 in the case of Freesurfer. Should I update my MNE version (i.e., 0.21.0) or replace some code lines with one equivalent command of Freesurfer (https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferCommands)? 

Best.

**Comment by agramfort** [comment]
hum this is bad as this command is required by MNE

@buildqa @mshamalainen we need to see how to proceed as it seems freesurfer
broke mne flash bem :(

>

**Comment by hoechenberger** [comment]
Interestingly this change does not seem to be listed in the release notes at https://surfer.nmr.mgh.harvard.edu/fswiki/ReleaseNotes

**Comment by RickLicona** [comment]
It seems that I need to download an old version of Free Surfer. Can you suggest me the correct version to avoid this error message?. 

Thanks!

**Comment by RickLicona** [comment]
Update: It is the same error with Free Surfer 7.1.0. Thus, 7.1.1 and 7.1.0 versions provided the same error message:
```
Processing sub001
  Skipping reconstruction (folder exists)
  Making BEM
('error: mri_make_bem_surfaces has been removed from this version of freesurfer. For further information, please post to the help list at freesurfer@nmr.mgh.harvard.edu\n', '')
```

```
-------- freesurfer-darwin-macOS-7.1.0-20200511-813297b --------
Setting up environment for FreeSurfer/FS-FAST (and FSL)
FREESURFER_HOME   /Applications/freesurfer/7.1.0
FSFAST_HOME       /Applications/freesurfer/7.1.0/fsfast
FSF_OUTPUT_FORMAT nii.gz
SUBJECTS_DIR      /Applications/freesurfer/7.1.0/subjects
MNI_DIR           /Applications/freesurfer/7.1.0/mni

```

**Comment by hoechenberger** [comment]
You will need to use FreeSurfer 6 for now, which can be downloaded from https://surfer.nmr.mgh.harvard.edu/fswiki/rel6downloads

**Comment by RickLicona** [comment]
> You will need to use FreeSurfer 6 for now, which can be downloaded from https://surfer.nmr.mgh.harvard.edu/fswiki/rel6downloads

Thanks! Now it is working. To avoid some problems in the case of **Mac Os X** , it is neccesary to **add a patch (https://drive.google.com/file/d/1ezjiNIbGNrNAiYD5ciYxMO2SK-R5vz9A/view)** for the **FreeSurfer 6**.  

See more regarding Mac Os X patch: https://www.mail-archive.com/freesurfer@nmr.mgh.harvard.edu/msg64333.html

**Comment by agramfort** [comment]
FYI we contacted freesurfer core dev team to try to fix this issue

cc @buildqa

thanks for the detailed report

>

**Comment by agramfort** [comment]
FYI mri_make_bem_surfaces has been put back on the freesurfer source tree so it should be fixed in the next release.

thanks @RickLicona for reporting the issue.

**Comment by jhouck** [comment]
FWIW mri_make_bem_surfaces is missing from freesurfer's Ubuntu 18 build, but support for that build is likely to be phased out soon.  Still present for all newer builds. See https://www.mail-archive.com/freesurfer@nmr.mgh.harvard.edu/msg73261.html
